word:
  number_of_answers: 2
  number_per_page: 3
  number_per_lesson: 2
user:
  number_per_page: 3
category:
  number_per_page: 3
filter:
  Alphabet: alphabet
  Learned: learned
  Not_Learned: not_learned
